### PR TITLE
Improve build system

### PR DESCRIPTION
**Pull request by dakejahl**
I took the opportunity while cherry picking your changes to look at your project and see how you were doing things. I saw some low hanging fruit that should help make your life a bit easier and speed up your builds

- Included mavlink-cpp as a submodule, you don't have to do the build/install dance, it's easier to just include it in the source build tree.

- Statically link libraries and include in build and include them as submodules (mavlink-cpp and airspyhf). This allows you to `make build` with both of your library dependencies included so you can develop  and test on your dev machine.

- Update Dockefile to use [dakejahl/arm64v8-focal](https://hub.docker.com/repository/docker/dakejahl/arm64v8-focal) which already has a bunch of build tools preinstalled. Copy entire project into docker image and then build. Like you mentioned using ssh submodules doesn't work well with Dockerfiles, also downloading the repo everytime is a waste of time.

The docker build is much faster now at 97s from a totally clean build (previously was 285s)

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
The submodule thing makes a ton of sense, thanks. I won’t be needing dockerfiles any more since I’m moving over to an RPi from the Skynode.

From: Jacob Dahl ***@***.***>
Date: Saturday, November 12, 2022 at 4:40 PM
To: DonLakeFlyer/MavlinkTagController ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DonLakeFlyer/MavlinkTagController] Improve build system (PR #1)

I took the opportunity while cherry picking your changes to look at your project and see how you were doing things. I saw some low hanging fruit that should help make your life a bit easier and speed up your builds

  *   Included mavlink-cpp as a submodule, you don't have to do the build/install dance, it's easier to just include it in the source build tree.
  *   Statically link libraries and include in build and include them as submodules (mavlink-cpp and airspyhf). This allows you to make build with both of your library dependencies included so you can develop and test on your dev machine.
  *   Update Dockefile to use dakejahl/arm64v8-focal<https://hub.docker.com/repository/docker/dakejahl/arm64v8-focal> which already has a bunch of build tools preinstalled. Copy entire project into docker image and then build. Like you mentioned using ssh submodules doesn't work well with Dockerfiles, also downloading the repo everytime is a waste of time.

The docker build is much faster now at 97s from a totally clean build (previously was 285s)

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/DonLakeFlyer/MavlinkTagController/pull/1

Commit Summary

  *   8f206b2<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/commits/8f206b2bd3f836e56f0444ea8471eaae3000f274> update includes
  *   fb83692<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/commits/fb836920c35ed3ed4de94ea8e037f20e437daf6e> added mavlink-cpp as submodule
  *   71a26ae<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/commits/71a26ae79448b17aec576af1f05376c06544aee8> improved docker build
  *   2a12f2a<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/commits/2a12f2ab15a504a4bb67287b1cb7d3f4f78a5fbf> added airspyhf as a submodule and link statically, clean up docker build

File Changes

(13 files<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/files>)

  *   M .gitmodules<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/files#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584> (6)
  *   M CMakeLists.txt<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a> (10)
  *   M CommandHandler.h<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/files#diff-86511efd41dc570e0c9e5cb496a70f5b2b459adeb9bd46cb3f02db93325b6658> (2)
  *   M Dockerfile<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557> (68)
  *   M UDPPulseReceiver.cpp<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/files#diff-9543e958a52dd0c1b26d650f41691e6dc5b2b01d4eed44ad7acd496f5053de90> (2)
  *   M UDPPulseReceiver.h<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/files#diff-ce3e013357a4b55e024f40da45eaae44d7b01dd5d21a99ccb6edfa9c0f60b073> (2)
  *   A libraries/CMakeLists.txt<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/files#diff-b21c578a48185d0906bc48ba22e79e64006a9873165c63f869f45021f85eb9fe> (5)
  *   A libraries/airspyhf<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/files#diff-d7777b97144a58acdf34415c914ec789d30af13ef8b8b94da6b6a0a8050f4925> (1)
  *   A libraries/mavlink-cpp<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/files#diff-88948e87e02251e2dd9e82abe9ec05a37ab37d74fa2c2d5e6a4123eb1238949d> (1)
  *   M main.cpp<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/files#diff-608d8de3fba954c50110b6d7386988f27295de845e9d7174e40095ba5efcf1bb> (4)
  *   D mavlink-headers<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/files#diff-256ce693e441f031ec3df3a4f3a775dc6ed3b6289a61b6de42ce6469922046c8> (1)
  *   M sendTunnelMessage.cpp<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/files#diff-efa4b01af8e2905ff2d1fb2b1a559ba17a0ff49afefd350da3f3675f8a1545af> (2)
  *   M sendTunnelMessage.h<https://github.com/DonLakeFlyer/MavlinkTagController/pull/1/files#diff-fba0d54610a5535dbbcaf27cf99deb20817af9acea42f0d05467c63a26efef2b> (2)

Patch Links:

  *   https://github.com/DonLakeFlyer/MavlinkTagController/pull/1.patch
  *   https://github.com/DonLakeFlyer/MavlinkTagController/pull/1.diff

**Comment by dakejahl** [comment]
You'll probably still want to cross compile your binary using the docker image and then copy the file from the container back to the host
https://stackoverflow.com/questions/25292198/docker-how-can-i-copy-a-file-from-an-image-to-a-host

**Comment by DonLakeFlyer** [comment]
Hmm, interesting. I’ve just been compiling everything on the RPi after I test on desktop. Certainly faster than compiling my crazy big matlab converted signal processing stuff on the RPi.

From: Jacob Dahl ***@***.***>
Date: Saturday, November 12, 2022 at 5:20 PM
To: DonLakeFlyer/MavlinkTagController ***@***.***>
Cc: Donald Gagne ***@***.***>, Comment ***@***.***>
Subject: Re: [DonLakeFlyer/MavlinkTagController] Improve build system (PR #1)

You'll probably still want to cross compile your binary using the docker image and then copy the file from the container back to the host
https://stackoverflow.com/questions/25292198/docker-how-can-i-copy-a-file-from-an-image-to-a-host

**Comment by dakejahl** [comment]
Yeah it's going to be way faster to cross compile. Also means you don't need all of the build tools on target and you're not risking forgetting to delete your source on target (if you care)

**Pull request closed without merging**
